RecordFCS_Alt/Models/DBModels/Movimientos/MovimientoAutorizacion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RecordFCS_Alt.Models
{
    public class MovimientoAutorizacion
    {
        [Key]
        public int MovimientoAutorizacionID { get; set; }

        [ForeignKey("Usuario1")]
        public Guid? Usuario1ID { get; set; }
        
        [ForeignKey("Usuario2")]
        public Guid? Usuario2ID { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime? FechaAutorizacion1 { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime? FechaAutorizacion2 { get; set; }


        //virtual
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }


    }
}

RecordFCS_Alt/Models/DBModels/Movimientos/MovimientoPieza.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RecordFCS_Alt.Models
{
    public class MovimientoPieza
    {
        [Key]
        [Column(Order = 1)]
        [ForeignKey("Movimiento")]
        public Guid MovimientoID { get; set; }

        [Key]
        [Column(Order = 2)]
        [ForeignKey("Pieza")]
        public Guid PiezaID { get; set; }

        public string Comentario { get; set; }
        public bool estaDisponible { get; set; }

        //Virtuales
        public virtual Pieza Pieza { get; set; }
        public virtual Movimiento Movimiento { get; set; }
    }
}

RecordFCS_Alt/Controllers/BaseController.cs
using RecordFCS_Alt.Helpers;
using RecordFCS_Alt.Helpers.Seguridad;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecordFCS_Alt.Controllers
{
    public class BaseController : Controller
    {
        protected virtual new CustomPrincipal User
        {
            get { return HttpContext.User as CustomPrincipal; }
        }

        protected virtual Boolean IsAuthenticated
        {
            get
            {
                if (HttpContext.User.Identity.IsAuthenticated)
                { return true; }
                else
                { return false; }

            }
        }

        /* ALERTAS */
        public void AlertaSuccess(string mensaje, bool descartable = false)
        {
            AddAlerta(AlertaEstilos.Success, mensaje, descartable);
        }

        public void AlertaInfo(string mensaje, bool descartable = false)
        {
            AddAlerta(AlertaEstilos.Info, mensaje, descartable);
        }

        public void AlertaWarning(string mensaje, bool descartable = false)
        {
            AddAlerta(AlertaEstilos.Warning, mensaje, descartable);
        }

        public void AlertaDanger(string mensaje, bool descartable = false)
        {
            AddAlerta(AlertaEstilos.Danger, mensaje, descartable);
        }

        public void AlertaInverse(string mensaje, bool descartable = false)
        {
            AddAlerta(AlertaEstilos.Inverse, mensaje, descartable);
        }

        public void AlertaDefault(string mensaje, bool descartable = false)
        {
            AddAlerta(AlertaEstilos.Default, mensaje, descartable);
        }



        private void AddAlerta(string alertaEstilo, string mensaje, bool descartable)
        {
            var alertas = TempData.ContainsKey(Alerta.TempDataKey)
                ? (List<Alerta>)TempData[Alerta.TempDataKey]
                : new List<Alerta>();

            alertas.Add(new Alerta
            {
                AlertaEstilo = alertaEstilo,
                Mensaje = mensaje,
                Descartable = descartable
            });

            TempData[Alerta.TempDataKey] = alertas;
        }

        public ActionResult _Alertas()
        {
            return PartialView("_Alertas");
        }


    }
}

RecordFCS_Alt/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecordFCS_Alt.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error/400
        public ActionResult SolicitudIncorrecta()
        {
            Response.StatusCode = 400;

            ViewBag.NoError = 400;
            ViewBag.TituloError = "Solicitud Incorrecta.";
            ViewBag.DescripcionError = "Contacte al administrador si persiste el error.";

            //Enlace
            ViewBag.LinkURLError = Url.Action("Index", "Home", null);
            ViewBag.LinkIconoError = "fa fa-home fa-align-vertical";
            ViewBag.LinkTituloError = " Inicio";

            return View("ErrorGeneral");
        }


        // GET: Error/401
        public ActionResult AccesoDenegado()
        {
            Response.StatusCode = 401;

            ViewBag.NoError = 401;
            ViewBag.TituloError = "Lo sentimos , no cuentas con los permisos para acceder.";
            ViewBag.DescripcionError = "Contacte al administrador si persiste el error.";

            //Enlace
            ViewBag.LinkURLError = Url.Action("Index", "Home", null);
            ViewBag.LinkIconoError = "fa fa-home fa-align-vertical";
            ViewBag.LinkTituloError = " Inicio";

            return View("ErrorGeneral");
        }


        // GET: Error/404
        public ActionResult NoEncontrado()
        {
            Response.StatusCode = 404;

            ViewBag.NoError = 404;
            ViewBag.TituloError = "Lo sentimos, la página solicitada no se encontro!";
            ViewBag.DescripcionError = "Contacte al administrador si persiste el error.";

            //Enlace
            ViewBag.LinkURLError = Url.Action("Index", "Home", null);
            ViewBag.LinkIconoError = "fa fa-home fa-align-vertical";
            ViewBag.LinkTituloError = " Inicio";

            return View("ErrorGeneral");
        }

        // GET: Error/405
        public ActionResult MetodoNoPermitido()
        {
            Response.StatusCode = 405;

            ViewBag.NoError = 405;
            ViewBag.TituloError = "El método de acceso al recurso no es permitido";

            ViewBag.DescripcionError = "Contacte al administrador si persiste el error.";

            ViewBag.LinkURLError = Url.Action("Index", "Home", null);
            ViewBag.LinkIconoError = " fa fa-home fa-align-vertical";
            ViewBag.LinkTituloError = " Inicio";

            return View("ErrorGeneral");
        }

        // GET: Error/408
        public ActionResult TiempoEsperaAgotado()
        {
            Response.StatusCode = 408;

            ViewBag.NoError = 408;
            ViewBag.TituloError = "Tiempo de espera agotado";

            ViewBag.DescripcionError = "Contacte al administrador si persiste el error.";

            ViewBag.LinkURLError = Url.Action("Index", "Home", null);
            ViewBag.LinkIconoError = " fa fa-home fa-align-vertical";
            ViewBag.LinkTituloError = " Inicio";

            return View("ErrorGeneral");
        }

        // GET: Error/500
        public ActionResult Error()
        {
            Response.StatusCode = 500;

            ViewBag.NoError = 500;
            ViewBag.TituloError = "Error del sistema.";
            ViewBag.DescripcionError = "Contacte al administrador si persiste el error.";

            //Enlace
            ViewBag.LinkURLError = Url.Action("Index", "Home", null);
            ViewBag.LinkIconoError = "fa fa-home fa-align-vertical";
            ViewBag.LinkTituloError = " Inicio";

            return View("ErrorGeneral");
        }




    }
}

RecordFCS_Alt/Controllers/MovimientoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RecordFCS_Alt.Models;
using PagedList;
using RecordFCS_Alt.Helpers.Seguridad;
using RecordFCS_Alt.Models.ViewsModel;
using System.Globalization;

namespace RecordFCS_Alt.Controllers
{
    public class MovimientoController : BaseController
    {
        private RecordFCSContext db = new RecordFCSContext();
        [CustomAuthorize(permiso = "")]
        // GET: Movimiento
        public ActionResult Index()
        {
            ViewBag.TipoMovimientoID = new SelectList(db.TipoMovimientos, "TipoMovimientoID", "Nombre");

            var mov = new Movimiento()
            {
                HaciaExposicion = false,
                FechaHoraMovimiento = DateTime.Now
            };

            var listaUbicaciones = db.Ubicaciones.Where(a => a.Status).Select(a => new { a.Nombre, a.UbicacionID }).OrderBy(a => a.Nombre);

            ViewBag.UbicacionDestinoID = new SelectList(listaUbicaciones, "UbicacionID", "Nombre");
            ViewBag.UbicacionOrigenID = new SelectList(listaUbicaciones, "UbicacionID", "Nombre");


            return View(mov);
        }


        public List<string> getListaCamposMostrar(string tipoMovimiento, EstadoMovimiento estado)
        {

            List<string> lista = new List<string>();


            //lista = new List<string>() { 
            //                "movhaciaExpo","movFolio","movTipo","movStatus","movFechaRet", "observa", //movimiento 1
            //                "odOrigen","odDestino","odFecha","odColeccion", //movimiento 2
            //                "solNombreSol","solCargoSol","solInstitucion","solNombreRepre","solCargoRepre","solSede","SolPaisEdo","solPeticionRec","solDicCondEspa","solCartaAcep","solContratoCom","solRevGuion","solCondicConserv","solFacilReport","solDictSegu","solListAval","solTramFianza","solPoliSeg","solPoliCartas", //solicitante
            //                "expoTitulo","espoCurador","expoFechaIni","expoFechaFIn",//exposicion
            //                "resNombre","resInstitu","resFechaSal", //responsable
            //                "autUsuario1","autUsuario2","autFecha1","autFecha2", //autorizacion
            //                "transNombre","transRecorr","transHorario","transNota", //transporte
            //                "segNombre","segPoliza","segFechaIni","segFechaFin", //seguro
            //                "pestSol", "pestRes", "pestAut", "pestTran", "pestSeg" //pestañas
            //            };

            //lista.Add("");
            switch (tipoMovimiento.ToLower())
            {
                case "ingreso":
                    if (estado == EstadoMovimiento.EnRegistro)
                        lista = new List<string>() { 
                            "movhaciaExpo","movFolio","movTipo","movStatus", "observa", //movimiento 1
                            "odOrigen","odDestino","odFecha","odColeccion", //movimiento 2
                            "solNombreSol","solCargoSol","solInstitucion","solNombreRepre","solCargoRepre","solSede","SolPaisEdo","solPeticionRec","solDicCondEspa","solCartaAcep","solContratoCom","solRevGuion","solCondicConserv","solFacilReport","solDictSegu","solListAval","solTramFianza","solPoliSeg","solPoliCartas", //solicitante
                            "expoTitulo","espoCurador","expoFechaIni","expoFechaFIn",//exposicion
                            "resNombre","resInstitu", //responsable
                            "autUsuario1","autUsuario2","autFecha1","autFecha2", //autorizacion
                            "transNombre","transRecorr","transHorario","transNota", //transporte
                            "segNombre","segPoliza","segFechaIni","segFechaFin", //seguro
                            "pestSol", "pestRes", "pestAut", "pestTran", "pestSeg" //pestañas
                        };


                    break;
                case "externo":
                    if (estado == EstadoMovimiento.EnRegistro)
                        lista = new List<string>() { 
                            "movhaciaExpo","movFolio","movTipo","movStatus", "observa", //movimiento 1
                            "odOrigen","odDestino","odFecha","odColeccion", //movimiento 2
                            "solNombreSol","solCargoSol", //solicitante
                            "expoTitulo","espoCurador","expoFechaIni","expoFechaFIn",//exposicion
                            //"resNombre","resInstitu","resFechaSal", //responsable
                            "autUsuario1","autUsuario2","autFecha1","autFecha2", //autorizacion
                            //"transNombre","transRecorr","transHorario","transNota", //transporte
                            //"segNombre","segPoliza","segFechaIni","segFechaFin" //seguro
                            "pestSol", "pestAut" //pestañas
                        };

                    break;

                case "salida":
                    if (estado == EstadoMovimiento.EnRegistro)
                        lista = new List<string>() { 
                            "movhaciaExpo","movFolio","movTipo","movStatus", "observa", //movimiento 1
                            "odOrigen","odDestino","odFecha","odColeccion", //movimiento 2
                            "solNombreSol","solCargoSol","solInstitucion","solNombreRepre","solCargoRepre","solSede","SolPaisEdo","solPeticionRec","solDicCondEspa","solCartaAcep","solContratoCom","solRevGuion","solCondicConserv","solFacilReport","solDictSegu","solListAval","solTramFianza","solPoliSeg","solPoliCartas", //solicitante
                            "expoTitulo","espoCurador","expoFechaIni","expoFechaFIn",//exposicion
                            "resNombre","resInstitu", //responsable
                            "autUsuario1","autUsuario2","autFecha1","autFecha2", //autorizacion
                            "transNombre","transRecorr","transHorario","transNota", //transporte
                            "segNombre","segPoliza","segFechaIni","segFechaFin", //seguro
                            "pestSol", "pestRes", "pestAut", "pestTran", "pestSeg" //pestañas

                        };

                    break;

                case "traslado":
                    if (estado == EstadoMovimiento.EnRegistro)
                        lista = new List<string>() { 
                            "movhaciaExpo","movFolio","movTipo","movStatus", "observa", //movimiento 1
                            "odOrigen","odDestino","odFecha","odColeccion", //movimiento 2
                            "solNombreSol","solCargoSol","solInstitucion","solNombreRepre","solCargoRepre","solSede","solRevGuion","solCondicConserv","solPoliSeg","solPoliCartas", //solicitante
                            "expoTitulo","espoCurador","expoFechaIni","expoFechaFIn",//exposicion
                            //"resNombre","resInstitu","resFechaSal", //responsable
                            "autUsuario1","autUsuario2","autFecha1","autFecha2", //autorizacion
                            "transNombre","transRecorr","transHorario","transNota", //transporte
                            //"segNombre","segPoliza","segFechaIni","segFechaFin" //seguro
                            "pestSol", "pestAut", "pestTran" //pestañas
                        };

                    break;
            }



            return lista;
        }


        // GET: Movimiento/Crear
        [CustomAuthorize(permiso = "")]
        public ActionResult Crear(Guid? TipoMovimientoID, bool? HaciaExposicion)
        {

            bool HaciaExposicionValor = HaciaExposicion == null || HaciaExposicion == false ? false : true;

            bool esOK = true;

            var listaMovAceptados = new List<string>() { "externo", "ingreso", "salida", "traslado" };

            var tipoMov = db.TipoMovimientos.Find(TipoMovimientoID);

            esOK = tipoMov == null ? false : true;


            esOK = esOK ? listaMovAceptados.Any(a => a == tipoMov.Nombre.ToLower()) : false;

            List<string> listaCampos = new List<string>();

            if (esOK)
            {

                int UltimoFolioMov = db.Movimientos.Select(a => a.FolioMovimiento).OrderByDescending(a => a).FirstOrDefault();

                var mov = new Movimiento()
                {
                    EstadoMovimiento = EstadoMovimiento.EnRegistro,
                    FolioMovimiento = UltimoFolioMov + 1,
                    HaciaExposicion = HaciaExposicionValor,
                    TipoMovimiento = tipoMov,
                    TipoMovimientoID = tipoMov.TipoMovimientoID,
                    ColeccionTexto = "Museo Soumaya"
                };

                listaCampos = getListaCamposMostrar(tipoMov.Nombre, EstadoMovimiento.EnRegistro);
                
                if (HaciaExposicionValor)
                {
                    mov.MovimientoExposicion = new MovimientoExposicion();
                    listaCampos.Add("pestExpo");
                }

                switch (tipoMov.Nombre.ToLower())
                {
                    case "externo":
                        mov.MovimientoSolicitante = new MovimientoSolicitante();
                        //mov.MovimientoAutorizacion = new MovimientoAutorizacion();
                        break;
                    case "ingreso":
                        mov.MovimientoSolicitante = new MovimientoSolicitante();
                        mov.MovimientoResponsable = new MovimientoResponsable();
                        //mov.MovimientoAutorizacion = new MovimientoAutorizacion();
                        mov.MovimientoTransporte = new MovimientoTransporte();
                        mov.MovimientoSeguro = new MovimientoSeguro();

                        break;
                    case "salida":
                        mov.MovimientoSolicitante = new MovimientoSolicitante();
                        mov.MovimientoResponsable = new MovimientoResponsable();

RecordFCS_Alt/Views/Movimiento/Delete.cshtml
@model RecordFCS_Alt.Models.Movimiento

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autorizacion.FechaAutorizacion1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autorizacion.FechaAutorizacion1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exposicion.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exposicion.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Responsable.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Responsable.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seguro.AseguradorNombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seguro.AseguradorNombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Solicitante.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Solicitante.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoMovimiento.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoMovimiento.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Transporte.EmpresaNombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Transporte.EmpresaNombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UbicacionDestino.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UbicacionDestino.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UbicacionOrigen.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UbicacionOrigen.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FolioMovimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FolioMovimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoMovimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoMovimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaRet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaRet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaMovimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaMovimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraMovimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraMovimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinutoMovimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinutoMovimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ColeccionTexto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColeccionTexto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observaciones)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RecordFCS_Alt/Views/Movimiento/_CrearLista.cshtml
<span>Partial View, Prueba de Crear Lista</span>

RecordFCS_Alt/Views/Movimiento/_Error.cshtml
<h2 class="text-danger">@ViewBag.Mensaje</h2>

RecordFCS_Alt/Views/Movimiento/_ResultadosBusqueda.cshtml
@model PagedList.IPagedList<Guid>
@using PagedList.Mvc;
@using RecordFCS_Alt.Helpers

@{
    string tipo = ViewBag.tipo;
    string listaNombre = "listaMov";
    Guid? UbicacionOrigenID = ViewBag.UbicacionOrigenID;
    bool  recargarListaTemp = ViewBag.recargarListaTemp;

}

<link href="~/Content/piezaMini.css" rel="stylesheet" />


<div>
    <p class="text-center">
        Selecciona las piezas a las cuales se aplicara el movimiento
        <br />
        <span id="AddPiezasAll" title="Agregar piezas seleccionadas" data-toggle="tooltip" class="btn btn-success btn-sm">Agregar piezas <span class='fa fa-chevron-right'></span></span>
    </p>

</div>

<ul class="media-list">

    @foreach (var piezaID in Model)
    {
        Html.RenderAction("FichaMini", "Movimiento", new { id = piezaID, UbicacionOrigenID = UbicacionOrigenID, tipoAttBuscar = "guion", listaNombre = listaNombre, esBusqueda = true });

        @*<li class="media">
                <div class="media-body">
                    @piezaID.ToString()
                </div>
            </li>*@
    }
</ul>



<div id="contentPager" class="text-center center-block">
    @Html.PagedListPager(Model, pagina => Url.Action("BuscarPiezas", new { pagina = pagina, tipo = tipo, listaNombre = listaNombre }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< Inicio", LinkToPreviousPageFormat = "< Anterior", LinkToNextPageFormat = "Siguiente >", LinkToLastPageFormat = "Final >>", UlElementClasses = new[] { "pagination", "pagination-sm" } })
    <p>Total de piezas encontradas: @Model.TotalItemCount</p>
</div>


<script src="~/Scripts/add.toolTip.js"></script>




<script type="text/javascript">

    //Paginador cargar vista parcial en el div

    $("#contentPager a").on("click", function (e) {
        $.ajaxSetup({ cache: false });

        if ($(this).attr("href")) {

            var inputLetraFolioID = $('#LetraFolioID');
            var inputGuionID = $('#GuionID');
            var inputClaves = $('#claves');

            var ubicacionOrigenID = "";

            $("#UbicacionOrigenID option:selected").each(function () {
                ubicacionOrigenID += $(this)[0].value;
            });

            //alert(ubicacionOrigenID);
            $('#renderResultadosBusqueda').html('' +
                '<div class="text-center">' +
                    '<p>' +
                        '<span class="text-muted">' +
                            'Por favor espere' +
                        '</span>' +
                    '</p>' +
                    '<i class="fa fa-spinner fa-pulse fa-12x text-muted"></i>' +
                    '<p>' +
                        'Se estan procedando los resultados...' +
                    '</p>' +
                '</div>');

            //var liga = $(this).attr("href").split('?');
            //var pag = liga[1].split('=');

            //$('#pag').val(pag[1]);



            $.ajax({
                url: this.href,
                type: 'GET',
                data: {
                    LetraFolioID: inputLetraFolioID.val(),
                    GuionID: inputGuionID.val(),
                    claves: inputClaves.val(),
                    UbicacionOrigenID: ubicacionOrigenID,
                    listaNombre : '@listaNombre'
                },
                success: function (result) {
                    $('#renderResultadosBusqueda').html(result); //  Campo que actualizara
                }
            });




        }

        return false;
    });




    $('#AddPiezasAll').on("click", function () {


        var listaAdd = [];
        $('.checkAdd:checkbox:checked').each(function () {
            listaAdd.push($(this).data('myid'));
        });

        var esOk = false;

        var myurl = '@Url.Action("AddPieza", "Movimiento")';

        var id = "";
        var ubicacionId = "";
        var listaNombre = '@listaNombre';


        $("#UbicacionOrigenID option:selected").each(function () {
            ubicacionId += $(this)[0].value;
        });

        //alert(ubicacionId)
        if (ubicacionId != "") {


            //listaAdd.forEach(function (value, index) {
            //    alert("i: " + index + ", val: " + value);
            //})
            $.ajaxSetup({ cache: false });

            $.each(listaAdd, function (index, value) {

                id = value;

                $.ajax({
                    url: myurl,
                    type: 'GET',
                    async: false,
                    data: {
                        id: id,
                        UbicacionID: ubicacionId,
                        listaNombre: listaNombre
                    },
                    success: function (result) {
                        //$('#renderResultadosBusqueda').html(result); //  Campo que actualizara
                        if (result.success) {
                            esOk = true;
                        }
                        else {
                            $('[data-myid="' + result.piezaID + '"]').prop("checked", false);
                            $('[data-myid="' + result.piezaID + '"]').prop("disabled", true);
                        }

                    }
                });
            });

            $('#alertasDiv').load('@Url.Action("_Alertas", "Base",null)');

            if (esOk == true) {
                $('#refrescarListaTemporal').trigger("click");
            }
            
        }
        else {

            origenDestinoAlertaAdd();
            ubicacionOrigenIDAdd();

            //AlertaModal("Sin Ubicación: Por favor selecciona la ubicación origen.", true);
            AlertaModal("Sin Ubicación: Por favor selecciona la ubicación origen.", false);
        }
    });



    $(function () {
        var recargarListaTemp = '@recargarListaTemp';
        if (recargarListaTemp == 'True') {
            $('#refrescarListaTemporal').trigger("click");
        }
    });
    



</script>