RecordFCS_Alt/Models/DBModels/EstructuraObra/Atributos/AutorPieza.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RecordFCS_Alt.Models
{
    [MetadataType(typeof(AutorPiezaMetadata))]
    public partial class AutorPieza
    {
        [Key]
        [Column(Order = 1)]
        [ForeignKey("Pieza")]
        public Guid PiezaID { get; set; }

        [Key]
        [Column(Order = 2)]
        [ForeignKey("Autor")]
        public Guid AutorID { get; set; }

        public bool esPrincipal { get; set; }
        public string Prefijo { get; set; }
        public bool Status { get; set; }

        //Virtuales
        public virtual Pieza Pieza { get; set; }
        public virtual Autor Autor { get; set; }
    }

    public class AutorPiezaMetadata
    {
        [Display(Name = "Estado")]
        public bool Status { get; set; }

        [Display(Name = "Principal")]
        public bool esPrincipal { get; set; }
        
        [Display(Name = "Prefijo")]
        public string Prefijo { get; set; }
    }
}

RecordFCS_Alt/Controllers/AutorPiezaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RecordFCS_Alt.Models;
using RecordFCS_Alt.Helpers.Seguridad;

namespace RecordFCS_Alt.Controllers
{
    public class AutorPiezaController : BaseController
    {
        private RecordFCSContext db = new RecordFCSContext();

        // POST: AutorPieza/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(permiso = "attPNew")]
        public ActionResult Crear([Bind(Include = "PiezaID,AutorID,Status")] AutorPieza autorPieza, Guid AtributoID)
        {

            string renderID = "autor_" + autorPieza.PiezaID + "_";

            string texto = "";
            bool guardar = false;

            string valor = Request.Form["id_" + AtributoID].ToString();

            autorPieza.AutorID = new Guid(valor);

            //no existe el ListaValorID entonces actualizar el AtributoPiezaID con el ListaValorID
            if (db.AutorPiezas.Where(a => a.PiezaID == autorPieza.PiezaID && a.AutorID == autorPieza.AutorID).Count() == 0)
            {
                guardar = true;

                var autor = db.Autores.Find(autorPieza.AutorID);

                texto = autor.Nombre + " " + autor.Apellido;

                AlertaSuccess(string.Format("Autor: <b>{0}</b> se agregó.", autor.Nombre + "" + autor.Apellido), true);
                autorPieza.AutorID = autor.AutorID;

            }
            else
            {
                guardar = false;
                //alerta ya existe
            }


            if (guardar)
            {
                db.AutorPiezas.Add(autorPieza);
                db.SaveChanges();
                renderID += autorPieza.AutorID;
            }


            return Json(new { success = true, renderID = renderID, texto = texto, guardar = guardar });

        }


        // POST: AutorPieza/Editar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(permiso = "attPEdit")]
        public ActionResult Editar(AutorPieza autorPieza, Guid AtributoID, Guid LlaveID)
        {
            //validar errores y devolverlos a la vista
            string renderID = "autor_" + autorPieza.PiezaID + "_" + LlaveID;

            string texto = "";
            bool guardar = false;


            var autorPiezaAnterior = db.AutorPiezas.Find(autorPieza.PiezaID, LlaveID);

            if (autorPiezaAnterior == null)
            {
                guardar = false;
                //alerta no existe el atributo
            }
            else
            {
                string valor = Request.Form["id_" + AtributoID].ToString();

                autorPieza.AutorID = new Guid(valor);

                guardar = true;

                //no existe el ListaValorID entonces actualizar el AtributoPiezaID con el ListaValorID
                if (db.AutorPiezas.Where(a => a.PiezaID == autorPieza.PiezaID && a.AutorID == autorPieza.AutorID).Count() == 0)
                {

                    var autor = db.Autores.Find(autorPieza.AutorID);

                    var textoNombreAutor = autor.Nombre + " " + autor.Apellido;
                    var textoPrefijo = autorPieza.Prefijo == "" || autorPieza == null ? "" : autorPieza.Prefijo + ": ";

                    texto = string.Format("<span><b>{0}</b></span>{1}", textoPrefijo, textoNombreAutor);

                    AlertaSuccess(string.Format("Autor: <b>{0}</b> se actualizo a <b>{1}</b>.", autorPiezaAnterior.Autor.Nombre + "" + autorPiezaAnterior.Autor.Apellido, autor.Nombre + " " + autor.Apellido), true);
                    autorPieza.AutorID = autor.AutorID;

                }
                else
                {
                    //alerta ya existe
                    AlertaSuccess(string.Format("Autor: <b>{0}</b> se actualizo.", autorPiezaAnterior.Autor.Nombre + "" + autorPiezaAnterior.Autor.Apellido), true);

                }
            }

            if (guardar)
            {
                db.AutorPiezas.Remove(autorPiezaAnterior);
                db.SaveChanges();
                db.AutorPiezas.Add(autorPieza);
                db.SaveChanges();
            }


            return Json(new { success = true, renderID = renderID, texto = texto, guardar = guardar, tipo = "Autor" });
        }


        [CustomAuthorize(permiso = "attPDel")]
        public ActionResult Eliminar(Guid? id, Guid? AutorID)
        {
            if (id == null && AutorID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AutorPieza autorPieza = db.AutorPiezas.Find(id, AutorID);
            if (autorPieza == null)
            {
                return HttpNotFound();
            }

            return PartialView("_Eliminar", autorPieza);
        }

        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(permiso = "attPDel")]
        public ActionResult EliminarConfirmado(Guid id, Guid AutorID)
        {
            string btnValue = Request.Form["accionx"];

            AutorPieza autorPieza = db.AutorPiezas.Find(id, AutorID);

            var NombreTexto = autorPieza.Autor.Nombre + " " + autorPieza.Autor.Apellido;

            switch (btnValue)
            {
                case "eliminar":
                    db.AutorPiezas.Remove(autorPieza);
                    db.SaveChanges();
                    AlertaDanger(string.Format("Se elimino <b>{0}</b>", NombreTexto), true);
                    break;
                default:
                    AlertaDanger(string.Format("Ocurrio un error."), true);
                    break;
            }

            return Json(new { success = true, guardar = false });
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RecordFCS_Alt/Views/AutorPieza/_CampoRegistro.cshtml
@using RecordFCS_Alt.Models
@{
    bool EsMultipleValor = ViewBag.EsMultipleValor;
    Guid AtributoID = ViewBag.AtributoID;
    string ParametrosHTML = ViewBag.ParametrosHTML;
    Guid TipoAtributoID = ViewBag.TipoAtributoID;
    string TipoInput = ViewBag.TipoInput;
    string NombreAtt = ViewBag.NombreAtt;
    SelectList ListaAutoresID = (SelectList)ViewBag.AutorID;

}



<div class="well">

    <div class="input-group">
        @Html.DropDownList("id_" + AtributoID, ListaAutoresID, "- Elije una opción -", htmlAttributes: new { @class = "form-control", required = "required" })

        <span class="input-group-addon">        </span>

        <input id="buscar_@AtributoID" type="text" placeholder="Buscar autor" class="form-control" />

        @if (User.IsInRole("regValNew"))
        {
            <span class="input-group-addon">
                <input type="checkbox" id="checkAdd_@AtributoID" class="btnCheckAdd" data-toggle="tooltip" data-title="Buscar/Guardar">
            </span>
        }
        


        <span id="btnAccion_@AtributoID" name="Buscar" class="input-group-addon btn btn-default">
            <span class="fa fa-search"></span>
        </span>


    </div>

    @Html.ValidationMessage("id_" + AtributoID, new { @class = "text-danger" })


    <p>Lista de autores:</p>
    <ul id="listaValores_@AtributoID" class="media-list"></ul>

</div>



<script type="text/javascript">

    $('#btnAccion_@AtributoID').on("click", function (e) {


        var attID = '@AtributoID';
        var tipoAttID = '@TipoAtributoID';
        var $inputSelect = $('#id_' + attID);
        var $itemSelected = $inputSelect.find('option:selected');
        var $btnCheck = $('#checkAdd_' + attID);
        var $inputBuscar = $('#buscar_' + attID);

        var $btn = $('#btnAccion_@AtributoID');

        /*
        Elemento Seleccionado:
            Texto = $itemSelected.text()
            Valor o id = $itemSelected.val()

        Input Buscador
            Valor = $inputBuscar.val()

        Boton Checked
            Valor = $btnCheck.is(':checked')

        Atributos
            Mostrar: $btn.attr("name")
            Cambiar Valor :  $btn.attr("name","prueba")
        */

        if ($btn.attr("name") == "Agregar") {
            //alert("entro a agregar");

            var myUrl = '@Url.Action("Crear", "Autor", new { EsRegistroObra = true })';

            $.ajaxSetup({ cache: false });

            $('#miModalContenido').load(myUrl, function () {
                $('#Nombre').val($inputBuscar.val());

                $('#miModal').modal({
                    backdrop: 'static',
                    keyboard: true
                }, 'show');

                $("#miModal").css("z-index", "1500");

                bindForm_ListaAutorMultiple(this);
            });

            function bindForm_ListaAutorMultiple(dialog) {
                var attID = '@AtributoID';

                $('form', dialog).submit(function (e) {

                    var validarOK = false;


                    validarOK = $(this).validate().valid();

                    if (validarOK) {
                        $.ajax({
                            url: this.action,
                            type: this.method,
                            data: $(this).serialize(),
                            success: function (result) {
                                if (result.success) {
                                    $('#miModal').modal('hide');

                                    $('#buscar_' + attID).val($.trim(result.nombre));


                                    $('#checkAdd_' + attID).trigger("click");
                                    $('#btnAccion_' + attID).trigger("click");

                                    $('#alertasDiv').load('/Base/_Alertas');

                                } else {
                                    $('#miModalContenido').html(result);
                                    bindForm_ListaAutorMultiple(dialog);
                                }
                            }
                        });
                    }
                    return false;
                });

            }

            //mostrar modal para confirmar el campo que se va agregar

        }
        else {

            $.ajaxSetup({ cache: false });

            var myUrl = '@Url.Action("GenerarLista","Autor",null)';

            $inputSelect.html('<option> Cargando... </option>');

            $.ajax({
                url: myUrl,
                type: 'POST',
                data: { Filtro: $inputBuscar.val() },
                dataType: 'json',
                success: function (result) {

                    if (result.length) {
                        $inputSelect.html('<option> - Elije un resultado - </option>');

                        for (var i = 0; i < result.length; i++) {
                            $inputSelect.append('<option value = "' + result[i].AutorID + '">' + result[i].Nombre + '</option>');
                        }
                    }
                    else {
                        $inputSelect.html('<option> - Sin resultados - </option>');
                    }


                }
            });

            $inputSelect.focus();

        }

    });

    $('#checkAdd_@AtributoID').on("click", function (e) {


        var attID = '@AtributoID';
        var $btnCheck = $('#checkAdd_' + attID);
        var $btn = $('#btnAccion_@AtributoID');
        var $inputBuscar = $('#buscar_' + attID);


        if ($btnCheck.is(':checked')) {
            $btn.attr("name", "Agregar");
            $btn.html('<span class="fa fa-floppy-o"></span>');
            $btn.removeClass("btn-default");
            $btn.addClass("btn-success");

            $inputBuscar.attr("placeholder", "Guardar valor");

        }
        else {
            $btn.attr("name", "Buscar");
            $btn.html('<span class="fa fa-search"></span>');
            $btn.removeClass("btn-success");
            $btn.addClass("btn-default");

            $inputBuscar.attr("placeholder", "Buscar valor");

        }
    });


</script>



<script type="text/javascript">

    $('#id_@AtributoID').on("change", function (e) {

        var attID = '@AtributoID';
        var $inputSelect = $(this);
        var ul = $('#listaValores_' + attID);
        var $inputBuscar = $('#buscar_' + attID);

        var $itemSelected = $inputSelect.find('option:selected');

        if ($itemSelected.val() == "") {
            //alert("vacio: " + $itemSelected.text());

        }
        else {
            //alert("algo: " + $itemSelected.text());

            var id_temp = 'id_' + attID + '_' + $itemSelected.val();

            var existe = false;

            var i = ul.children().length;
            ul.find('li').each(function (i, li) {
                if ($(this).attr('id') == 'li_' + id_temp) {
                    existe = true;
                    //alert($(li).attr("id"));
                }
            });

            if (!existe) {

                var placeHolder = i == 0 ? "Principal" : "";

                var textAppend = '' +
                    '<li class="media" id="li_' + id_temp + '">' +
                    '   <div class="media-body">' +
                    '       <input type="hidden" id="' + id_temp + '" name="' + id_temp + '" value="' + $itemSelected.val() + '" />' +
                    '       <div class="form-group">' +
                    '           <div class="col-md-2 col-sm-2 col-xs-3">' +
                    '               <input type="text" id="' + id_temp + '_prefijo" name="' + id_temp + '_prefijo" value="' + placeHolder + '"  placeholder="Prefijo" class="form-control input-sm" />' +
                    '           </div>' +
                    '           <label class="control-label" for="' + id_temp + '_prefijo">' + $itemSelected.text() + '</label>' +
                    '       </div>' +
                    '   </div>' +
                    '   <span id="quitar_' + id_temp + '" class="btn btn-xs btn-danger media-right" data-toggle="tooltip" title="Quitar valor"><span class="fa fa-times"></span></span>' +
                    '</li>';


                ul.append(textAppend);

                $('#quitar_' + id_temp).addClass("quitarLiListaAutor_" + attID);
                $('#quitar_' + id_temp).tooltip();
            }





            //var stringHTML = '  <li class="media" id = "li_' + id_temp + '">';
            //stringHTML += '         <div class="media-body">';
            //stringHTML += '             <input type="hidden" ' + 'id="' + id_temp + '"  value = "' + $itemSelected.val() + '"/>';
            //stringHTML +=                   $itemSelected.text();
            //stringHTML += '             </div>' ;
            //stringHTML += '             <span id="quitar_' + id_temp + '" class="btn btn-xs btn-danger media-right" data-toggle="tooltip" title="Quitar valor"><span class="fa fa-times"></span></span>';
            //stringHTML += '     </li>';


            //ul.append(stringHTML);









            $inputBuscar.val('');
            $inputSelect.val('');




        }

        if (ul.html() == "") {
            $inputSelect.attr('required', true);
        }
        else {
            $inputSelect.attr('required', false);
        }


    });

    $(document.body).on("click", '.quitarLiListaAutor_' + '@AtributoID', function (e) {

        var attID = '@AtributoID';
        var ul = $('#listaValores_' + attID);
        var $inputSelect = $('#id_' + attID);

        $(this).parent().remove();

        if (ul.html() == "") {
            $inputSelect.attr('required', true);
        }
        else {
            $inputSelect.attr('required', false);
        }

    });
</script>

RecordFCS_Alt/Views/AutorPieza/_Crear.cshtml
@model RecordFCS_Alt.Models.AutorPieza

@{
    bool EsMultipleValor = ViewBag.EsMultipleValor;
    Guid AtributoID = ViewBag.AtributoID;
    string ParametrosHTML = ViewBag.ParametrosHTML;
    Guid TipoAtributoID = ViewBag.TipoAtributoID;
    string TipoInput = ViewBag.TipoInput;
    string NombreAtt = ViewBag.NombreAtt;
    SelectList ListaAutoresID = (SelectList)ViewBag.AutorID;

    Guid id = ViewBag.id;


}

@{
    ViewBag.PagName = "Crear ";
    ViewBag.CtrlName = NombreAtt;
}


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" data-toggle="tooltip" title="Cerrar">&times;</button>
    <h4 class="modal-title" id="myModalLabel">
        <b>@ViewBag.PagName</b>
        <i class="text-muted">@ViewBag.CtrlName</i>
    </h4>
</div>






@using (Html.BeginForm("Crear", "AutorPieza", FormMethod.Post, null))
{

    <div class="modal-body">

        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PiezaID)
            @Html.Hidden("AtributoID", AtributoID)

            <div class="input-group">
                @Html.DropDownList("id_" + AtributoID, ListaAutoresID, "- Elije una opción -", htmlAttributes: new { @class = "form-control", required = "required" })

                <span class="input-group-addon"></span>

                <input id="buscar_@AtributoID" type="text" placeholder="Buscar valor" class="form-control" />

                @if (User.IsInRole("catNew"))
                {
                    <span class="input-group-addon">
                        <input type="checkbox" id="checkAdd_@AtributoID" class="btnCheckAdd" data-toggle="tooltip" data-title="Buscar/Guardar">
                    </span>
                }
                


                <span id="btnAccion_@AtributoID" name="Buscar" class="input-group-addon btn btn-default">
                    <span class="fa fa-search"></span>
                </span>


            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.esPrincipal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.esPrincipal)
                        @Html.ValidationMessageFor(model => model.esPrincipal, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prefijo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Prefijo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Prefijo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        </div>


    </div>


    <div class="modal-footer">
        <button class="btn" type="button" data-dismiss="modal">Cancelar</button>
        <input class="btn btn-primary" type="submit" value="Guardar" />
    </div>

}





<script type="text/javascript">

    $('#btnAccion_@AtributoID').on("click", function (e) {


        var attID = '@AtributoID';
        var tipoAttID = '@TipoAtributoID';
        var $inputSelect = $('#id_' + attID);
        var $itemSelected = $inputSelect.find('option:selected');
        var $btnCheck = $('#checkAdd_' + attID);
        var $inputBuscar = $('#buscar_' + attID);

        var $btn = $('#btnAccion_@AtributoID');

        /*
        Elemento Seleccionado:
            Texto = $itemSelected.text()
            Valor o id = $itemSelected.val()

        Input Buscador
            Valor = $inputBuscar.val()

        Boton Checked
            Valor = $btnCheck.is(':checked')

        Atributos
            Mostrar: $btn.attr("name")
            Cambiar Valor :  $btn.attr("name","prueba")
        */

        if ($btn.attr("name") == "Agregar") {
            //alert("entro a agregar");

            var myUrl = '@Url.Action("Crear", "Autor", new { EsRegistroObra = true })';

            $.ajaxSetup({ cache: false });

            $('#miModalContenido').load(myUrl, function () {
                $('#Nombre').val($inputBuscar.val());

                $('#miModal').modal({
                    backdrop: 'static',
                    keyboard: true,

                }, 'show');

                $("#miModal").css("z-index", "1500");

                bindForm_ListaAutor(this);
            });

            function bindForm_ListaAutor(dialog) {


                var attID = '@AtributoID';

                $('form', dialog).submit(function (e) {

                    var validarOK = false;


                    validarOK = $(this).validate().valid();

                    if (validarOK) {
                        $.ajax({
                            url: this.action,
                            type: this.method,
                            data: $(this).serialize(),
                            success: function (result) {
                                if (result.success) {
                                    $('#miModal').modal('hide');

                                    $('#buscar_' + attID).val($.trim(result.nombre));

                                    $('#checkAdd_' + attID).trigger("click");
                                    $('#btnAccion_' + attID).trigger("click");

                                    $('#alertasDiv').load('/Base/_Alertas');

                                } else {
                                    $('#miModalContenido').html(result);
                                    bindForm_ListaAutor(dialog);
                                }
                            }
                        });
                    }
                    return false;
                });

            }

            //mostrar modal para confirmar el campo que se va agregar

        }
        else {

            $.ajaxSetup({ cache: false });

            var myUrl = '@Url.Action("GenerarLista","Autor",null)';

            $inputSelect.html('<option> Cargando... </option>');

            $.ajax({
                url: myUrl,
                type: 'POST',
                data: { id: tipoAttID, Filtro: $inputBuscar.val() },
                dataType: 'json',
                success: function (result) {

                    if (result.length) {
                        $inputSelect.html('<option> - Elije un resultado - </option>');

                        for (var i = 0; i < result.length; i++) {
                            $inputSelect.append('<option value = "' + result[i].AutorID + '">' + result[i].Nombre + '</option>');
                        }
                    }
                    else {
                        $inputSelect.html('<option> - Sin resultados - </option>');
                    }


                }
            });

            $inputSelect.focus();

        }

    });

    $('#checkAdd_@AtributoID').on("click", function (e) {

        var attID = '@AtributoID';
        var $btnCheck = $('#checkAdd_' + attID);
        var $btn = $('#btnAccion_@AtributoID');
        var $inputBuscar = $('#buscar_' + attID);


        if ($btnCheck.is(':checked')) {
            $btn.attr("name", "Agregar");
            $btn.html('<span class="fa fa-floppy-o"></span>');
            $btn.removeClass("btn-default");
            $btn.addClass("btn-success");

            $inputBuscar.attr("placeholder", "Guardar valor");

        }
        else {
            $btn.attr("name", "Buscar");
            $btn.html('<span class="fa fa-search"></span>');
            $btn.removeClass("btn-success");
            $btn.addClass("btn-default");

            $inputBuscar.attr("placeholder", "Buscar valor");

        }
    });

</script>



<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>

RecordFCS_Alt/Views/AutorPieza/_Eliminar.cshtml
@model RecordFCS_Alt.Models.AutorPieza
@{
    ViewBag.PagName = "Eliminar Autor";
    ViewBag.CtrlName = Model.Autor.Nombre + Model.Autor.Apellido;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" data-toggle="tooltip" title="Cerrar">&times;</button>
    <h4 class="modal-title" id="myModalLabel">
        <b>@ViewBag.PagName</b>
        <i class="text-muted">@ViewBag.CtrlName</i>
    </h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.AutorID)
    @Html.HiddenFor(model => model.PiezaID)
    
    <div class="modal-body">
        <div class="text-center">
            <h3>
                ¿Quieres
                <b class="text-danger">
                    ELIMINAR
                </b>
                el Autor de la pieza?
            </h3>

            <p>
                @Html.DisplayFor(model => model.Autor.Nombre)
                @Html.DisplayFor(model => model.Autor.Apellido)
            </p>
            <p>---</p>
            <p>Por favor confirma la acción:</p>

            <label class="text-danger">
                Eliminar
            </label>
            <input type="radio" name="accionx" value="eliminar" class="form-control" />


        </div>
    </div>

    <div class="modal-footer">

        <button class="btn" type="button" data-dismiss="modal">Cancelar</button>
        <input class="btn btn-danger" type="submit" value="Confirmar" />

    </div>

}

<script src="~/Scripts/add.toolTip.js"></script>